name: Suggestion
description: Suggest a change or new feature.
labels: ['➕ Suggestion']

body:
- type: markdown
  attributes:
    value: |
      ## 👋 Welcome to the SFMobDrops Suggestion Tracker
      Also take a look at the list of [existing Suggestions](https://github.com/Slimefun/Slimefun4/issues).
      Give a 👍 ️to any suggestions you like!
      <br /><strong><i>Fields marked with an asterisk (*) are required.</i></strong>
      <br />

- id: description
  type: textarea
  validations:
    required: true
  attributes:
    label: '📍 Description'
    description: |
      A clear and detailed description of what your suggestion is.
      The more information you can provide, the easier and more accurately it can be implemented.
    placeholder: |
      It would be great if we could do [...] it would provide the ability to do [...]s.

- type: markdown
  attributes:
    value: |
      ## ❤️ Thank you for submitting your suggestion! Suggestions improve the plugin and create better content for everyone!