name: SFMobDrops
description: Add random Slimefun mob drops
version: ${project.version}
api-version: 1.14
author: WalshyDev
main: dev.walshy.sfmobdrops.SfMobDrops
depend: [Slimefun]
softdepend:
  - GuizhanLibPlugin

commands:
  mobdrops:
    description: Mob drops
    aliases: [sfmobdrops, mobdrop, sfmd]
