name: Publish build

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Upload build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn clean package

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: SFMobDrops
          releaseChannel: Dev
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
